version: 1

formatters:
    fileFormatter:
        format: '%(levelname)9s %(asctime)s %(filename)25s: %(lineno)3s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    consoleFormatter:
        format: '%(levelname)9s %(asctime)s %(thread)20d %(filename)25s: %(lineno)3s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        formatter: consoleFormatter
        level: INFO
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        formatter: fileFormatter
        level: DEBUG
        filename: log_exception.LOG
    asset_file:
        class: logging.FileHandler
        formatter: fileFormatter
        level: DEBUG
        filename: log_asset.LOG

loggers:
    sLogger:
        level: DEBUG
        handlers: [file]
    assetLogger:
        level: DEBUG
        handlers: [asset_file]

root:
    level: DEBUG
    handlers: [console]
